prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
prometheusOperator:
  admissionWebhooks:
    failurePolicy: Ignore
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: argo-cd-grafana
    additionalScrapeConfigs: |
      - job_name: 'argocd'
        scrape_interval: 30s
        scrape_timeout: 10s
        static_configs:
          - targets: ['argocd-application-controller-metrics.argocd.svc.cluster.local:8082', 'argocd-redis-metrics.argocd.svc.cluster.local:9121']
      - job_name: 'alertManager'
        scrape_interval: 30s
        scrape_timeout: 10s
        static_configs:
          - targets: ['alertmanager-operated.argocd.svc.cluster.local:9093']
alertmanager:
  enabled: true
nodeExporter:
  enabled: false
